clientId: <enter your client id>
clientSecret: <enter your client secret>
authorizationCode: <enter your authorization code>

redirectUrl: https://app.getpostman.com/oauth2/callback
tokenEndpoint: https://accounts.spotify.com/api/token

userPlaylistsEndpoint: https://api.spotify.com/v1/me/playlists
